spring.application.name=franchise

spring.datasource.url=jdbc:mysql://localhost:3306/abacus_v3
spring.datasource.username=root
spring.datasource.password=root
#abacusAdmin@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port:1001

#file.upload-dir=C:/Images/


# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


#Use For Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=geniushr25@gmail.com
spring.mail.password=wyynrbpezsvafjnh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



#Use For Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html



#use for S3 backet Image
# File upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#aws
#aws.s3.bucket-name=abacusexambucket
#aws.s3.region=us-east-1
#aws.s3.access-key=AKIAQKGGW425D7NCC4US
#aws.s3.secret-key=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
#aws.s3.url=https://abacusexambucket.s3.us-east-1.amazonaws.com/
#aws.s3.connection-timeout=300000 # 5 minutes
#aws.s3.request-timeout=300000 # 5 minutes


#
#spring.datasource.hikari.maximum-pool-size=1
#spring.datasource.hikari.minimum-idle=1
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.pool-name=SingleConnectionPool

# JWT Configuration
jwt.access.secret=THIS_IS_MY_SUPER_SECRET_KEY_FOR_JWT_SIGNING_256_BIT